### ISSUE TITLE
redis-datasource dependency

### ISSUE THREAD

**Issue by ulgena** [RedisGrafana/grafana-redis-app#108]
### Is your enhancement related to a problem? Please describe.
There is no bug or problem

### Describe the solution you'd like
Review on "redis-app" plugin dependency to redis-datasource v2.2.0 or >v2.1.1

### Describe alternatives you've considered
Specifying "GF_INSTALL_PLUGINS" in proper order to override dependancy problem.
Grafana will install first install redis-datasource v2.1.1, then redis-app v2.2.1 and finally will install redis-datasoruce v2.2.0

#### Working example for docker-compose.yml Grafana service definition :
```
grafana:
    image: "grafana/grafana:9.5.14"
    container_name: grafana
    hostname: grafana
    user: "0"
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./etc/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - ./data/grafana/:/var/lib/grafana/
    # TODO : Add new plugings to be installed within below variablenpde 
    environment:
      GF_INSTALL_PLUGINS: >-
        redis-app 2.2.1,
        redis-explorer-app 2.1.1
        redis-datasource 2.2.0,
    networks:
      redis-network:
        ipv4_address: 172.18.100.9
    ports:
      - "3000:3000"
    logging: *default-logging
```

#### Grafana logs for downgrading redis-datasource for redis-app plugin installation :

```
✔ Downloaded and extracted redis-datasource v2.2.0 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded and extracted redis-app v2.2.1 zip successfully to /var/lib/grafana/plugins/redis-app

Fetching redis-datasource dependency...

✔ Downloaded and extracted redis-datasource v2.1.1 zip successfully to /var/lib/grafana/plugins/redis-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.

✔ Downloaded and extracted redis-explorer-app v2.1.1 zip successfully to /var/lib/grafana/plugins/redis-explorer-app

Fetching redis-app dependency...

✔ Downloaded and extracted redis-app v2.2.1 zip successfully to /var/lib/grafana/plugins/redis-app

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```
